### PR TITLE
fix(multiCheckbox): Set 'required' validation only when desired. Clos…

### PR DESCRIPTION
**Pull request by m0t0r**
…es #37

### CODE REVIEW

**Comment by kentcdodds** [comment]
Looks good. I'll release when I get to my laptop.

**Comment by m0t0r** [comment]
Cool :+1:

**Comment by kentcdodds** [comment]
Thanks! Released as `5.0.2`

**Comment by m0t0r** [comment]
Nice, I'm glad to help ;)

**Pull request merged**
