### PR TITLE
[addon] inject $event.

### PR DESCRIPTION
**Pull request by aitboudad**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Hi @aitboudad, thanks for the contribution!

This project uses semantic-release to automatically release a new version as soon as commits get into master. To do this, it follows a commit message convention. Could you please amend your commit message to follow that convention so your contribution will be released following our standard process. You can find out more about our convention [here](https://github.com/formly-js/angular-formly/blob/master/CONTRIBUTING.md#pull-requests).

Thanks again! This is great!

**Comment by kentcdodds** [comment]
Oh, and let me know when you're done. GitHub won't notify me when a pull request has been updated.

**Comment by aitboudad** [comment]
@kentcdodds done

**Comment by kentcdodds** [comment]
Thanks!

**Pull request merged**
